### ISSUE TITLE
Show more than one suggestion (Enhancement)

### ISSUE THREAD

**Issue by phlind** [Clemens-E/obsidian-languagetool-plugin#1]
Hey, as of now it only displays the first suggestion to fix a grammar error. Would it be possible to show more (maybe 2)? What would be great is if it would be the same interface as in a text field on a website (allowing to double-click for synonyms etc.). But maybe that's not possible?

**Comment by Clemens-E** [comment]
fixed, you can manually install the latest tag, I will add this to the plugin list in the near future
