### ISSUE TITLE
Cannot install plugin from community plugins page

### ISSUE THREAD

**Issue by shuyunzhang99** [Clemens-E/obsidian-languagetool-plugin#10]
When accessing LanguageTool Integration from Community plugins within Obsidian, an alert comes up that states that it has failed to install. Occurring on the latest insider builds of macOS (intel) and iPad mobile app.

**Comment by Clemens-E** [comment]
Obsidian looks at the master branch to check for the latest version (doesn't make any sense because it downloads from the releases) and GitHub actions is currently down (see https://www.githubstatus.com), so I guess I will have to manually release it
