### ISSUE TITLE
FR: Let Eslint & Stylelint fix style issues in CI and push those fixes directly into the repo

### ISSUE THREAD

**Issue by Raboro** [Clemens-E/obsidian-languagetool-plugin#101]
In the CI Es- & Stylelint are already used. But if they found a issues, the build fails and you need to fix those changes manuelly and push it again and so on. This is redundant and could be automated. 
In the `lint.yml` file there must be a section thats fixes those issues and push it into the repo. After that there should be a validation step, where both linters are triggered again to check if all the issues are fixed and if not now the push fails. 
I already done this a couple of times and it´s not a big change, just around 10 lines of code.

**Comment by Clemens-E** [comment]
Thank you, but I prefer it to be passive.
