### ISSUE TITLE
Missing Functionality: Jump to Previous Suggestion

### ISSUE THREAD

**Issue by blay** [Clemens-E/obsidian-languagetool-plugin#102]
It would be great to have a shortcut to jump backward to the previous suggestion from the cursor position. As you are typing, you can then fix your latest error. 

There is already a hotkey to "Jump to next Suggestion" so I assume it would be a minor change to add "previous" as well.

**Comment by Clemens-E** [comment]
You will see the option after the next release, which should be sometime today.
