### ISSUE TITLE
[Question] Would it be possible to enhance the plugin to autocorrect as I type?

### ISSUE THREAD

**Issue by thesamim** [Clemens-E/obsidian-languagetool-plugin#103]
In case it's not clear what I'm asking: a la Google Docs or Microsoft Word that will automagically correct words as I'm typing if the error is reasonable to detect.

Feels like most of the hard work is done in this plugin. :) 

I imagine the challenge would be in detecting which corrections are most likely to be the "correct" spelling.

**Comment by Clemens-E** [comment]
I think the challenge would be calling the language tool rest API on as you are typing without reaching the rate limit
