### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by dario-baumberger** [Clemens-E/obsidian-languagetool-plugin#108]
I've installed the languagetoolplus plugin in my vault. The vault is synced to multiple devices (Windows, MacOs, iPadOs and iOs). The plugin doesn't work anymore. I haven't used obsidian for a while. no idea when this started. When I click check document (or check automatically), this message appears in the obsidian interface: 
![image](https://github.com/Clemens-E/obsidian-languagetool-plugin/assets/10287381/5e332641-88f7-457c-9e25-64b20793e1c3)

```
In the console the following errors are displayed:
Access to fetch at 'https://api.languagetoolplus.com/v2/check' from origin 'app://obsidian.md' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

```
Failed to load resource: net::ERR_FAILED https://api.languagetoolplus.com/v2/check
```

```
TypeError: Failed to fetch
    at eval (plugin:obsidian-languagetool-plugin:7:13028)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-languagetool-plugin:1:573)
    at new Promise (<anonymous>)
    at s (plugin:obsidian-languagetool-plugin:1:307)
    at gr (plugin:obsidian-languagetool-plugin:7:11617)
    at Rr.eval (plugin:obsidian-languagetool-plugin:7:40191)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-languagetool-plugin:1:573)
    at new Promise (<anonymous>)
    at s (plugin:obsidian-languagetool-plugin:1:307)
    at Rr.runDetection (plugin:obsidian-languagetool-plugin:7:39872)
    at Rr.eval (plugin:obsidian-languagetool-plugin:7:35046)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-languagetool-plugin:1:573)
    at new Promise (<anonymous>)
    at s (plugin:obsidian-languagetool-plugin:1:307)
    at eval (plugin:obsidian-languagetool-plugin:7:34803)
    at e.handleEvent (app.js:1:888522)
```

The last two arise from the first.

I have the following API settings (with a valid API key and my email address):
![image](https://github.com/Clemens-E/obsidian-languagetool-plugin/assets/10287381/c7fc9f72-53a2-4b64-a8cd-7c111142ee81)

Is there a solution for this from the plugin or the API. Or do I have to send the requests yourself via middleware?

**Comment by dario-baumberger** [comment]
I tried a few things. I looked at the plugin javascript file and formatted it (hence the high line numbers in the errors)

As soon as I have more than 7000 words in a document, an error 500 appears. With exactly 7000 words, the check works correctly without any errors.

```
POST https://api.languagetoolplus.com/v2/check 500
```

```
plugin:obsidian-languagetool-plugin:5795 Error: unexpected status 500, see network tab
    at eval (plugin:obsidian-languagetool-plugin:5565:133)
    at Generator.next (<anonymous>)
    at a (plugin:obsidian-languagetool-plugin:19:21)
```

Sometimes also error 504. But I haven't found any logic behind it yet.


As far as I could tell, the CORS error described above only occurs with documents that contain base64 images. Obsidian itself does not insert images into base64, the contents were copied and pasted from One Note.

Then I tried to bypass CORS in the plugin code. To do this, I set the following here https://github.com/Clemens-E/obsidian-languagetool-plugin/blob/master/src/api.ts#L87:
```
method: "POST",
                mode: "no-cors",
                body: Object.keys(u).map((e => `${encodeURIComponent(e)}=${encodeURIComponent(u[e])}`)).join("&"),
                headers: {
                    "Access-Control-Allow-Origin": "*",
                    "Content-Type": "application/x-www-form-urlencoded",
                    Accept: "application/json" 
                }
```

This resulted in an error 413

I would say the issue can be closed. The plugin works as it should. In special cases it has problems, but all in all: functions as designed.

**Comment by Clemens-E** [comment]
Thank you for investigating this

You could open an issue with languagetool for the 5xx errors.

**Comment by dario-baumberger** [comment]
For me it's okay like that. 

I had a quick look at the 5xx. Could be one of these reasons: 
- https://languagetool.org/http-api/
- https://dev.languagetool.org/public-http-api

With base64 images, I'm sure I have more than 30 misspelled words.
