### ISSUE TITLE
How to find the LT rule name in order to disable it

### ISSUE THREAD

**Issue by 0atman** [Clemens-E/obsidian-languagetool-plugin#116]
I would like to ignore some of the languagetool rules, but I can't figure out what the rule that is triggering this warning is.

Searching for "Oxford" in the [rule list](https://community.languagetool.org/rule/list?offset=0&max=10&lang=en&filter=oxford&categoryFilter=&_action_list=Filter) doesn't give oxford spelling rules, only 4 oxford comma rules, so I don't know what rule I have offended in order to silence it.

![2023-12-12 08-05-13-927840867](https://github.com/Clemens-E/obsidian-languagetool-plugin/assets/114097/cb844a93-cd65-4a12-b481-ee00f308b847)

Anyone know  what I should do here?

Huge thanks to @Clemens-E for making this plugin, my life as a professional writer has DRAMATICALLY improved since discovering this plugin! :heart:

**Comment by Clemens-E** [comment]
Thanks to @brandones and his PR #110 there is now an "i" button in the modal, displaying the matching category and rule.

**Comment by 0atman** [comment]
oh fantastic! Thank you @brandones and @Clemens-E :heart:

**Comment by 0atman** [comment]
AHA IT WAS `BRE_STYLE_OXFORD_SPELLING` GET REKT OXFORD! :tada: 

(thanks folks!)
