### ISSUE TITLE
Enable project sponsorships

### ISSUE THREAD

**Issue by 0atman** [Clemens-E/obsidian-languagetool-plugin#117]
@Clemens-E as I mentioned in [the other issue](https://github.com/Clemens-E/obsidian-languagetool-plugin/issues/116) I just opened, I'm a professional writer and producer (here's [a video on Obsidian](https://www.youtube.com/watch?v=DbsAQSIKQXk&t=290s) I wrote... in Obsidian, using Obsidian Advanced Slides, spelling and grammar checked with your plugin).

I try to support open-source tools that literally put food on my table, my [podcast](https://www.youtube.com/watch?v=p3bDE9kszMc&list=PL95NP4bDITAln7fq-cCqzOFE15UvVthuL&index=2) and YouTube 'empire' is built on the shoulders of the giants of our incredible community!

Please [enable github sponsorships](https://github.blog/2020-03-24-getting-started-with-github-sponsors/) for this project, I won't be the only person who will thank you :smile: 

> Note: I recognise the project is in maintenance mode, this doesn't represent me sneakily forcing you to spend time improving it, it's already 99% feature complete as far as I'm concerned, I want you to be rewarded for the EXISTING value that we all get out of it. If I have a feature I want, I'm a coder, I'll make a PR <3

**Comment by Clemens-E** [comment]
Hi! As far as I know, I would have to apply to a waitlist to be a sponsored user.
However, the project already has a Sponsor button that links to ko-fi, I feel a little ashamed asking for donations while not committing anything in 6 Months, but I could probably fill 90% of my spare time with all the open issues and feature requests.
Maybe I will take some fixed time per week/day to work on the plugin that I will not exceed

**Comment by 0atman** [comment]
That's interesting, I had no problem setting up sponsorship for https://github.com/0atman/noboilerplate 
(I don't remember if there was a waitlist? If there was, it was so fast I don't remember waiting.) 
Give it a try! :smiley:

**Comment by Clemens-E** [comment]
You are correct, the waitlist was one second.
There appears to be an approval wait for adding bank accounts, and stripe wants all of my personal and tax information, so I don't really intend to do this as it's much easier to collect donations via Ko-Fi, 
Thank you for the donation!

**Comment by 0atman** [comment]
My pleasure! 

Perhaps a patreon? I find their experience really lovely, and recurring payments are important. Though having said that, ko-fi supports those too!

Github is pretty decent at putting other funding sources in the same place as their native funding, look at my project for example:
![2023-12-15 15-08-21-628516793](https://github.com/Clemens-E/obsidian-languagetool-plugin/assets/114097/25a2647e-a39b-4fda-a7b1-fdfa1a46d990)

Anyway, thank you again for this great plugin! :-)
