### ISSUE TITLE
Request to Language Tool Failed

### ISSUE THREAD

**Issue by dkp** [Clemens-E/obsidian-languagetool-plugin#119]
Mac OS 13.6.1 Ventura; Obsidian 1.5.3 (and previous versions had the same issue).

I am badgered almost constantly by a message: Request to LanguageTool failed; Check plugin settings for logs.
I HAVE checked the plugin settings

<img width="411" alt="dMRI_afqstats_project_-_work_-_Obsidian_v1_5_3" src="https://github.com/Clemens-E/obsidian-languagetool-plugin/assets/965184/66ecd7a7-9528-4d86-8225-83502ab3a2d5">

The request logs do not appear to contain anything.  
Sorry, bummed ; (

**Comment by Clemens-E** [comment]
Can you show your configs?

**Comment by dkp** [comment]
Sorry, I'm not sure how to export these choices, so here's a screenshot:

<img width="960" alt="Screenshot_1_3_24__3_04_PM" src="https://github.com/Clemens-E/obsidian-languagetool-plugin/assets/965184/fee0d119-2bfa-443b-89fd-3305a277a303">

**Comment by Clemens-E** [comment]
I'm assuming that you have API username and apikey configured but removed them for this screenshot?

**Comment by dkp** [comment]
I have not configured those as I am not a paying customer ; (
Is that the only way the extension will behave?

**Comment by Clemens-E** [comment]
In this case you have to change the "Endpoint" setting to "Standard". Right now it's set to "Premium"

**Comment by dkp** [comment]
Thank you.  I'll try that.  I appreciate your time.
