### ISSUE TITLE
AutoCheck Delay (ms) Slider Settings Ui Bug

### ISSUE THREAD

**Issue by Eight-P** [Clemens-E/obsidian-languagetool-plugin#121]
The AutoCheck Delay (ms) option slider is not changing/can't be moved.
(other sliders in other menus work fine for me)

Obsidian v1.5.3
LanguageTool Plugin v0.3.6

**Comment by Clemens-E** [comment]
Should be fixed.
Just a heads-up, with the standard URL the lower limit is 3000ms due to rate-limiting.

**Comment by Eight-P** [comment]
Awesome, thank you.
