### ISSUE TITLE
UK English Spellings

### ISSUE THREAD

**Issue by Sprocketer** [Clemens-E/obsidian-languagetool-plugin#125]
@Clemens-E Currently English spellings e.g. "summarise" are being marked with a suggestion to change to the -ize ending when both mother tongue and Interpret English as settings are set to British English. - fix pls

**Comment by TenEXP** [comment]
This is not a bug, you need to disable Oxford Spelling Rules, as seen in #116.
![image](https://github.com/Clemens-E/obsidian-languagetool-plugin/assets/79748192/e4714f50-fc79-40d6-8bf4-44f40420f7e3)
