### ISSUE TITLE
Autocheck function erasing text  

### ISSUE THREAD

**Issue by kerim** [Clemens-E/obsidian-languagetool-plugin#128]
I had to disable the "Autocheck Text" command because it was erasing the last thing I typed.

Using Obsidian 1.6.0 (insider release), and a Premium account on a Macbook Pro.

**Comment by ATJonzie** [comment]
I'm having the same issue!

**Comment by Clemens-E** [comment]
Please add any new findings new to #92
As long as nobody can reliably replicate this bug, it's really complicated to fix.
I will give it a shot today, but no guarantees

@tutunak "paid users"? You pay absolutely nothing, no idea what you're on to.
