### ISSUE TITLE
The v0.0.8 build has the wrong version number in the manifest

### ISSUE THREAD

**Issue by vulpes2** [Clemens-E/obsidian-languagetool-plugin#16]
The v0.0.8 build has the wrong version number in the manifest, the manifest still says v0.0.7. It causes Obsidian to repeatedly prompt for updates.

![image](https://user-images.githubusercontent.com/83679347/119661889-c2a70280-bdfe-11eb-8826-6f74adfc8115.png)

https://github.com/Clemens-E/obsidian-languagetool-plugin/releases/tag/0.0.8

**Comment by Clemens-E** [comment]
Thanks for reporting, should be fixed.
