### ISSUE TITLE
What URL to use for a selfhosted server?

### ISSUE THREAD

**Issue by brimwats** [Clemens-E/obsidian-languagetool-plugin#18]
I am hosting my own LanguageTool. The URL it uses for the plugin is https://plugin.subdomain.tld/v2—but when I put that into the plugin settings it reports "failed". Any insight?

**Comment by Clemens-E** [comment]
The URL should be `https://domain.ltd`
I can add that as example so its clearer

**Comment by brimwats** [comment]
Confirming that that works! It would definitely help to have it in docs :)
