### ISSUE TITLE
When an incorrect word is on the side of the text, the popup is cutoff for correction

### ISSUE THREAD

**Issue by Braweria** [Clemens-E/obsidian-languagetool-plugin#20]
This image will show what I mean:  

![image](https://user-images.githubusercontent.com/62669899/119952589-77772600-bf9d-11eb-9948-146f3b8bf0af.png)

Related, but has no comments and is from March: https://github.com/Clemens-E/obsidian-languagetool-plugin/issues/5

**Comment by Clemens-E** [comment]
related..?
Its the same issue

**Comment by Braweria** [comment]
The issue is related, *because* it's the same issue. The older issue had no comments and thus I have created a new one. In neither, you mentioned if that is something you already knew about or working on it or any kind of indication, so I cannot know that part when creating a new issue. I never said it's a different issue.  
Hope that clears it up.

**Comment by vulpes2** [comment]
I believe this bug has now been fixed.

**Comment by Braweria** [comment]
@vulpes2 i can confirm it has
