### ISSUE TITLE
Language checking inside Mathjax blocks

### ISSUE THREAD

**Issue by SkepticMystic** [Clemens-E/obsidian-languagetool-plugin#22]
Perhaps related to #13, Language Tool gives false suggestions for content inside Mathjax blocks

![image](https://user-images.githubusercontent.com/70717676/123225445-06ab2700-d4d3-11eb-9e42-876fb33630f7.png)

**Comment by Clemens-E** [comment]
I dont know how that works, but I assume everything inbetween of $ $ is considered MathJax and should be ignored?
could be fixed with https://github.com/micromark/micromark-extension-math

**Comment by SkepticMystic** [comment]
Yes, everything inside two dollars is mathjax. It is already built-in to Obsidian, so I don't want to use a different extension for that

**Comment by mgmeyers** [comment]
This should be fixed now in v0.1.2. @Clemens-E I didn't realize micromark extensions could be added! I'll remove my hackier approach in favor of those.
