### ISSUE TITLE
The plugin does not report errors anymore when the server is unreacheable

### ISSUE THREAD

**Issue by vulpes2** [Clemens-E/obsidian-languagetool-plugin#24]
Since v0.0.9, the plugin no longer reports any errors with a popup when it cannot reach a LanguageTool server, thus there is no longer an indication on why the plugin doesn't do anything when a custom URL was not configured correctly. It would be nice if basic error reporting could be added back.

**Comment by wenlzhang** [comment]
I tried to configure a local server by following the guide as follows and did not get any error or response either.

[LanguageTool embedded HTTP Server | dev.languagetool.org](https://dev.languagetool.org/http-server)

**Comment by vulpes2** [comment]
@mgmeyers Thanks for the fix :+1:
