### ISSUE TITLE
Extend the feature to Antidote

### ISSUE THREAD

**Issue by trungng2006** [Clemens-E/obsidian-languagetool-plugin#25]
Hello,
May I ask if you could also extend this plugin for antidote?
https://www.antidote.info/en
https://antidote.readthedocs.io/en/stable/reference.html

**Comment by Clemens-E** [comment]
Hi, with the current information, unlikely, because 
1. I can not find relevant documentation about any API (an HTTP API would be optimal)
2. the documentation you linked is for a dependency injection framework for python

**Comment by mgmeyers** [comment]
I found this: https://www.antidote.info/en/antidote-10/documentation/developer-tools

But the JS api seems to rely on the browser plugin being active. I agree that it doesn't seem possible to integrate with antidote.

**Comment by trungng2006** [comment]
Thank you so much for investing time to consider my request!
