### ISSUE TITLE
How to configure this plugin for LanguageTool Desktop version for offline use?

### ISSUE THREAD

**Issue by wenlzhang** [Clemens-E/obsidian-languagetool-plugin#28]
I set up the LanguageTool server URL as `http://localhost:8081`, according to the tutorial given below:
[LanguageTool embedded HTTP Server | dev.languagetool.org](https://dev.languagetool.org/http-server)

With this setting, I got the following error when trying to use this plugin from Obsidian: Request to LanguageTool Server failed.

As a reference, the LanguageTool local server is set up for TeXstudio as follows, and it works for TeXstudio.
<img width="923" alt="Screenshot 2021-07-16 at 09 39 24" src="https://user-images.githubusercontent.com/44930227/125910810-356fd81b-f0dc-4330-8d7f-3334f502cae1.png">

**Comment by Clemens-E** [comment]
How did you configure it in Obsidian?
and also, to figure out the exact error, please follow my instruction/video in the other issue
https://github.com/Clemens-E/obsidian-languagetool-plugin/issues/15#issuecomment-846607182

**Comment by wenlzhang** [comment]
Thanks for the prompt response!

In Obsidian, I configured the LanguageTool Endpoint as `http://localhost:8081`, and the default values are used for all other settings. Also, it works when checking with the default LanguageTool Endpoint.

Following the instructions, I got nothing in the Preview tab. Content in the Headers and Preview can be seen in the following screenshots:

![Screenshot 2021-07-16 at 10 08 21](https://user-images.githubusercontent.com/44930227/125915276-3ef9f6e5-4470-4db8-8d39-6022262e283b.png)
![Screenshot 2021-07-16 at 10 08 04](https://user-images.githubusercontent.com/44930227/125915308-3e58674f-c4f3-45e5-85bd-5115d2654262.png)

**Comment by vulpes2** [comment]
Have you tried starting LT _outside_ of TeXStudio as a troubleshooting measure? LT will print errors in the console if the request has issues. Try `java -jar languagetool.jar` and just enable HTTP server in the settings menu.
![image](https://user-images.githubusercontent.com/83679347/126071221-092d7929-4438-4bb8-abf9-1b338f9faedb.png)

**Comment by wenlzhang** [comment]
Thanks a lot for the help! @vulpes2 

After starting the LanguageTool java application outside TeXstudio, this plugin works like a charm now! Besides, I noticed the following:

- Since the default port number 8081 is used in my TeXstudio, a different port number, e.g. 8082, needs to be used when setting the LanguageTool java application.
- For this plugin to work, the LanguageTool java application needs to be running.
  - An interesting observation, though, is that this plugin would give grammar hints even when the LanguageTool java application is closed, if this particular note has been checked before.

Not sure why one needs to set different port numbers to make LanguageTool work for this plugin and TeXstudio at the same time, but it works now. 👍 

Still, it would be nice to be able to make LanguageTool work for this plugin without running the LanguageTool java application, if this is possible.

**Comment by vulpes2** [comment]
You may simply disable the autostart behavior in TeXStudio and point it to the same LT server instance you just started. However, I understand this Java GUI is somewhat inconvenient and it takes up space on the system tray. You could potentially look into running the server it in a docker container instead: https://hub.docker.com/r/erikvl87/languagetool

Additionally, I think we can mark this issue as resolved for now, since it's out of scope for this plugin.

**Comment by wenlzhang** [comment]
Thank you @vulpes2 for the suggestion on using the docker container as a workaround! I would explore this option later on.
