### ISSUE TITLE
Text not legible

### ISSUE THREAD

**Issue by phlind** [Clemens-E/obsidian-languagetool-plugin#3]
Hey, I was just testing version 0.0.2. For me, it looks like this... The information text is not legible due to missing background:

![Bildschirmfoto 2021-03-11 um 16 37 30](https://user-images.githubusercontent.com/30386310/110812873-446ba300-8288-11eb-803d-8bb32260a6c0.png)

**Comment by Clemens-E** [comment]
Hi, what theme is that?
I think it's because of a missing variable, I should probably add a check for that

**Comment by phlind** [comment]
It's the default theme.

**Comment by WakanaYuki** [comment]
@phlind I have created a pull request, that fixed the issue a bit.

**Comment by Clemens-E** [comment]
should be fixed, if it doesnt work for your specific theme you can enable the glass background in the plugins settings
please report back and close the issue if its fixed, thanks!

**Comment by phlind** [comment]
Yes, the problem is fixed now, thanks!
