### ISSUE TITLE
Premium Account support and synonyms

### ISSUE THREAD

**Issue by Superelmanu** [Clemens-E/obsidian-languagetool-plugin#32]
Hello, I love the integration of LanguageTool in Obsidian. I have been a dyslexic how to have to work in 3 different languages and this is the only tool that help me.

I'm a premium user of the tool and I do wonder if there is a way too:

* Have the premium feature hooked in your plugin?
* Have access to synonyms?

This is a fantastic integration and a lifesaver for me. 
Thank you

**Comment by Clemens-E** [comment]
Accessing Premium Features is only possible if you pay for access to the API, see #8 

For synonyms, I don't know, what is the condition to get those over the API?

**Comment by functionalStoic** [comment]
Hi @Clemens-E,
I pay for premium and have received API access by requesting it. Any chance this feature could be added?
Thanks!

**Comment by Clemens-E** [comment]
Would have been practical if you mentioned this before I deleted the feature because I thought nobody has access unless paying a lot anyway 🙂

I will see what I can do.

**Comment by functionalStoic** [comment]
Thanks @Clemens-E
Apologies for missing that conversation. Appreciate your help!

**Comment by Clemens-E** [comment]
Hi, @functionalStoic 
Sorry for taking so long, you can test the new feature in the attached zip. If you can confirm it works, please lmk and I will create a new release
[obsidian-languagetool-plugin.zip](https://github.com/Clemens-E/obsidian-languagetool-plugin/files/7123706/obsidian-languagetool-plugin.zip)

**Comment by Superelmanu** [comment]
> Hi @Clemens-E,
> I pay for premium and have received API access by requesting it. Any chance this feature could be added?
> 
> I'd happily pay for your account for a few months if it helped prioritization 😀
> Thanks!

How do you get your API from LanguageTool?

**Comment by Clemens-E** [comment]
I am interested in that too. Some premium users have told me that you do not have API access when paying for a Premium Account. You would have to pay quite a high fee for that.

**Comment by Superelmanu** [comment]
I'm paying for a premium account, but nowhere near to $60 a month… more like $80 a year. 
Am I missing something?

**Comment by Superelmanu** [comment]
I reach out to them asking about the procedure to get an API number when you are already paying premium membership. 
I will keep you posted as soon as they answer.

**Comment by functionalStoic** [comment]
Hi @Clemens-E / @Superelmanu,
I sent in a simple support request for the feature to be enabled. They asked me the use-case. I explained it was for my personal use and not a paid Integration that should build it in as a feature and use the API directly.

I'll try out the beta version mentioned above and let you know how it goes.

**Comment by functionalStoic** [comment]
Hi @Clemens-E,

I tested using with/without username & password of a word within my Personal Dictionary, and it appears to work as expected based on highlighting in Obsidian. Also, I compared the Network Requests made in Obsidian with that made using the LanguageTool API page, and they match.

If there is anything else specific you'd like to test before merging, just let me know.

I really appreciate your effort here. Let me know how I can thank you!

**Comment by Superelmanu** [comment]
Here is the answer from LanguageTool. @functionalStoic I do not understand how you got the API number. 

“Probably a good idea is to try our brand-new Windows desktop app.
We just released it, and you can correct texts via shortcut from all desktop apps, which we don't have an extension for.
Please get further information about the desktop app here: https://languagetool.org/windows
​
If you want to purchase the API only, you can have a look at the following page: https://languagetool.org/proofreading-api
The pricing of our API depends on the daily requests you would send. “

**Comment by Clemens-E** [comment]
I just installed their new desktop app and looks like it allows you to select text, press a shortcut, and then that text is in their app. Not ideal IMO

**Comment by Superelmanu** [comment]
Yes, I agree, this is not the best workflow. 
How did you get an API number from them? There feed back on using the Windows app, it's not great.

**Comment by Clemens-E** [comment]
About the synonyms:
I asked LanguageTool if I can use their endpoint for synonyms (which isn't documented and can't be self hosted).
They said yes, but its not really meant for the public and could change at any time.
I'm going to implement that

**Comment by Superelmanu** [comment]
> About the synonyms:
> I asked LanguageTool if I can use their endpoint for synonyms (which isn't documented and can't be self hosted).
> They said yes, but its not really meant for the public and could change at any time.
> I'm going to implement that

Thai is fantastic and pretty much the only thing I need. Writing in a language which is not your own make you look bad if you do not have access to synonyms.
Thank you for this @Clemens-E

**Comment by janpeeters70** [comment]
Hi all, Thanks for developing this great plugin @Clemens-E It's a great addition and very useful! 
I purchased a premium subscription yesterday to be able to use their professoinal API and filled in my email address, the API key and the end point URL (it's different from the one which was preconfigured) in the Obsidian Languagetool settings. When I choose to check the document, I get a notification saying "Request to LanguageTool failed." I would love to get this working. Can someone help me out? 
Thanks, Jan

**Comment by janpeeters70** [comment]
> I am interested in that too. Some premium users have told me that you do not have API access when paying for a Premium Account. You would have to pay quite a high fee for that.

They told me that they offered this as an option for premium users. After I purchased premium I requested access and they made it available in my account settings. At no extra cost.

**Comment by Mara-Li** [comment]
@janpeeters70 how did you contact them? By mail? Which mail? I'm pretty interested

**Comment by janpeeters70** [comment]
Hi @Mara-Li I used sales@languagetoolplus.com. I explained to them that it's only for personal use and I included my subscription email address. 
They answered: "We can offer this as part of the premium subscription. Are you already a premium member? An account can be created on languagetool.org/premium."

**Comment by Mara-Li** [comment]
> Hi all, Thanks for developing this great plugin @Clemens-E It's a great addition and very useful! I purchased a premium subscription yesterday to be able to use their professoinal API and filled in my email address, the API key and the end point URL (it's different from the one which was preconfigured) in the Obsidian Languagetool settings. When I choose to check the document, I get a notification saying "Request to LanguageTool failed." I would love to get this working. Can someone help me out? Thanks, Jan

Okay, so now I have the same problem :(

**Comment by Clemens-E** [comment]
Hi @Mara-Li @janpeeters70 
I can't debug this because I don't have premium, so we have to do it this way.
1. URL
> the end point URL (it's different from the one which was preconfigured)

I can't test, but I don't think this is true.
On https://languagetool.org/http-api/swagger-ui/
it says to simply set the api key in the request, it shouldn't be a different URL, also @functionalStoic didn't mention changing it, and it worked for him.

2. follow the steps here and attach screenshots of the request body and response body and status
*make sure to blur out your api key*
https://github.com/Clemens-E/obsidian-languagetool-plugin/issues/15#issuecomment-846607182

**Comment by Mara-Li** [comment]
Here somes screenshot :
![image](https://user-images.githubusercontent.com/30244939/147826989-c1ffe836-c853-4a06-a707-54fcb5fd270f.png)
![image](https://user-images.githubusercontent.com/30244939/147826993-12ca0967-e953-4518-a4e3-3def3ec680a9.png)
![image](https://user-images.githubusercontent.com/30244939/147826995-e93347bb-7cbd-44b6-9bde-acc053cde0f9.png)

**Comment by Clemens-E** [comment]
Can you try changing the URL? I just saw this:
https://github.com/Clemens-E/obsidian-languagetool-plugin/issues/8#issuecomment-992414294

If that doesn't work, you have to contact LanguageTool themselves, this is either a temporary issue or bad error handling on their side.

"Internal Server Error" means there is an issue on their side.

**Comment by Mara-Li** [comment]
I try, but I have error too (another error, like they can access)

**Comment by Mara-Li** [comment]
Seems to work with this API ! 
Maybe add a note in the readme for that ?

**Comment by janpeeters70** [comment]
Yes this seems to work for me too! Thanks for the research.
