### ISSUE TITLE
Any chance to get languagetool pro service 

### ISSUE THREAD

**Issue by Enrico68** [Clemens-E/obsidian-languagetool-plugin#33]
Hello and thanks for this plugin (I am writing most of my texts in Deutsch, and this is the only way (till now) to have a spell-checking other than English. Problem is the number of characters allowed (not more than 20k). Is there in the near future an upgrade to the Pro-service?

**Comment by Clemens-E** [comment]
Wer lesen kann ist klar im Vorteil
#32 #8
