### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by Alan-Python** [Clemens-E/obsidian-languagetool-plugin#37]
Is there an LanguageTool add-on in Obsidian for iOS?

**Comment by Clemens-E** [comment]
No, mobile is currently not supported

**Comment by Alan-Python** [comment]
Why?

**Comment by Clemens-E** [comment]
Because I have a full time job and little free time, so I don't have the time or motivation to invest the work and time it requires to make this Plugin work with Mobile.
If you need it so dearly you are welcome to create a pull request.
