### ISSUE TITLE
compatibility with live preview editor

### ISSUE THREAD

**Issue by tubeldelta** [Clemens-E/obsidian-languagetool-plugin#39]
The new live preview mode that was introduced with Obsidian 0.13.0 breaks the plugin, and the spell check can't complete.

**Comment by Clemens-E** [comment]
I'm not an insider and cannot check compatibility with 0.13

**Comment by Mara-Li** [comment]
It also seems that the plugin doesn't load in "source mode" option. Dunno if it's because of Obsidian API or a bug on your side.
As you don't have the preview, you can't do anything so...

**Comment by mgmeyers** [comment]
So, it's currently impossible for this plugin to support the new live preview and "source" modes, and mobile as well. These all use codemirror 6, and plugin developers don't currently have the necessary means of interacting with the editor the way this language tool plugin needs.

To be more specific, we have no way of initializing codemirror 6 extensions.

From: https://codemirror.net/6/docs/migration/
> Marked text (and bookmarks) are called decorations in the new system, and creating them is a bit more difficult (but also a lot less error-prone).
>
> Instead of adding and removing marks through a side effect, decorations are provided by extensions, scoped to their source extension, and only present as long as that extension continues to provide them.
>
>That means you can't just call a method to mark some text, but have to define an extension to manage it.

**Comment by dariuszkowalski-com** [comment]
> So, it's currently impossible for this plugin to support the new live preview and "source" modes, and mobile as well.
That a pitty.  Maybe there is a way to achieve it in other way?

**Comment by chrisgrieser** [comment]
> So, it's currently impossible for this plugin to support the new live preview and "source" modes, and mobile as well

that really a bummer! Writing in Obsidian really takes a small hit with the new editor, since Vale, too, doesn't work there anymore.

I am also very interested if there is some other way around it

**Comment by mgmeyers** [comment]
So, this is now possible. Obsidian 0.13.8 introduced a codemirror 6 extension API, and it's just a matter of building a compatible extension.

**Comment by chrisgrieser** [comment]
@Clemens-E Any plans on updating the plugin for CM6? 🙏 
(no pressure! Just interested whether I should look for alternatives or just hold out a while.)

**Comment by mgmeyers** [comment]
@Clemens-E (cc: @chrisgrieser) I can raise a PR with CM6 support within the next day or two, if you're not already on it.

**Comment by Clemens-E** [comment]
I haven't looked into it because it's currently Christmas eve..

If you want you can work on it, otherwise I will dig into CM6 tomorrow evening (haven't done anything with it yet)

**Comment by mgmeyers** [comment]
Live preview is now supported in Obsidian 0.13.16

**Comment by chrisgrieser** [comment]
Thank you so much!!

**Comment by chrisgrieser** [comment]
btw, I just noticed by change that Language Tool does work in CM6 already (I am on Obsidian 0.13.14)
