### ISSUE TITLE
Suggestion based on words at end of line & beginning of next

### ISSUE THREAD

**Issue by JasonSooter** [Clemens-E/obsidian-languagetool-plugin#45]
First, Thanks for the plugin @Clemens-E and for the contribution to update to Live Preview @mgmeyers!

Occasionally (I've not determined the pattern), the checker will make a suggestion based on a merge of the end of one line and the beginning of another.

Here's a screenshot:
![2021-12-28_17-43-30](https://user-images.githubusercontent.com/7215306/147617379-4db99a24-ea1d-4f4a-bde6-0eefd0c3ba6e.png)

I tried adding a blank line, then deleting it, and it then made the same suggestion again.

Any ideas? Let me know if I can help with any specific troubleshooting.

**Comment by mgmeyers** [comment]
Hmm, I'm unable to reproduce this @functionalStoic. Could you send the exact markdown from the image above?

**Comment by functionalStoic** [comment]
Hi @mgmeyers,
Let me know if the below gives you what you need or if I can provide anything further (console, developer tools, etc.)

```
- Hmm, let's try to reproduce
	- i.e. how about now
	- i.e. like this
	- something besides i.e. though?
	- Does e.g. do it?
		- Apparently not
- No
	- i.e. hello
- well hmm
- Wait for it
	- because it may happen
- However
	- it might happen here awaiting a comma
- But it didn't

(without outliner)
Hmm, let's try to reproduce
i.e. how about now
Yes
```

<img width="395" alt="2022-01-01_16-06-30" src="https://user-images.githubusercontent.com/7215306/147861923-4f682127-2770-4dbe-acef-f723de66e53e.png">

Notes:
Obsidian Version:
- 0.13.7 (installer 0.13.4)

**Comment by gabrielwhite** [comment]
Same issue here:

<img width="705" alt="Screen Shot 2022-06-29 at 1 14 44 PM" src="https://user-images.githubusercontent.com/955848/176496937-7d7ff769-9474-4649-9231-1979edcc01b5.png">

Obsidian 0.14.15
Languagetool Plugin 0.2.7

I have a self-hosted languagetool (https://hub.docker.com/r/erikvl87/languagetool), running v5.7)

**Comment by mzietlow** [comment]
I am having a similiar issue with the Rule `UPPERCASE_SENTENCE_START`. I tried disabling it (+ restarting Obsidian), but whenever I start typing beneath a heading, LT suggests to lower case the next letter:

![image](https://user-images.githubusercontent.com/30702083/190871585-89ac1f4f-ad1b-4233-9032-61c67cd65925.png)

**Comment by mzietlow** [comment]
Turns out I've got it all wrong. Following the [basic markdown guidelines](https://www.markdownguide.org/basic-syntax/) (especially putting blank lines after headings...)  my issue vanished into thin air.
