### ISSUE TITLE
[Feature Request]: Keyboard shortcuts to navigate suggestions & Auto-correct

### ISSUE THREAD

**Issue by apotenza92** [Clemens-E/obsidian-languagetool-plugin#46]
Hi, great plugin thank you for providing this!

Was wondering if there are any plans to incorporate keyboard shortcuts to cycle through the corrections and bring up the correction pane or to auto-correct text based on the top suggestion automatically as you type?

**Comment by csss1234** [comment]
Yes I have the same question. How can we use the following?

from https://dev.languagetool.org/development-overview:

> You can switch on automatic application of suggestions by using --apply (or -a for short) on the command-line. Note: only the first suggestion is applied if the rule has more than one suggestion. Make sure that you only select the rules which are reliable enough to allow automatic correction (use the switch -e to select the rules you want to use, or -d to disable some of the rules). The suggestions are applied in the order of the starting position of errors in the text. Try to make some tests to see if you have clashing or conflicting suggestions. LanguageTool checks if the error found by the rule is still there in the text before applying the suggestion, but that’s the only quality check. The text is checked only once, so if multiple suggestions create an error that another rule could correct, you can simply run LT on the output from the previous check.

**Comment by d4rr3ll** [comment]
Just adding a +1 to this request.  It's one of the things I miss after moving to Obsidian from VSCode for all my Markdown.  Suggested workflow would be...

- place caret over word to correct
- Keyboard shortcut to open suggestions/corrections
- up/down arrow to select
- enter to activate/replace the word

**Comment by RasT110e5** [comment]
Adding a vote to this request. It completely breaks my flow to have to correct with the mouse.

**Comment by robinsonkwame** [comment]
+1, getting RSI from having to click X out of the spell check modals, for example.

**Comment by Clemens-E** [comment]
Late reply, but there are no plans for this feature, as this is not an issue in my workflow.
Leaving this issue open if someone wants to implement this.

**Comment by hpr1999** [comment]
I might have a look on the weekend then, if time permits. Haven't done work on obsidian plugins yet though, so definitely no promises.

**Comment by hpr1999** [comment]
Alright, I cobbled something together. While you didn't want to implement, would be open to have a look at the work I've done in #81 @Clemens-E?
