### ISSUE TITLE
LanguageTool plugin no longer remembers 'ignored suggestion'

### ISSUE THREAD

**Issue by Cmhorn** [Clemens-E/obsidian-languagetool-plugin#47]
I love the tool, but recently notice having to ignore the same suggestion over and over. Has something changed where the ignored suggestions are no longer remembered?

**Comment by mgmeyers** [comment]
Thanks for reporting this @Cmhorn. This got lost in the migration to the new obsidian editor. I'll look into adding back in

**Comment by almays** [comment]
Where does it store ignored words, personal dictionary? How can I clean it?

**Comment by Cmhorn** [comment]
Nowhere, now.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

------- Original Message -------

**Comment by Clemens-E** [comment]
@almays 
They are stored in obsidians spellcheckDictionary
you can find it in yourvault/.obsidian/app.json
I can't replicate, for me, it stores the ignored words and ignores them like it should

**Comment by Cmhorn** [comment]
It was months ago and already acknowledged as a bug. Probably got fixed. I just stopped using it. Not much use if it doesn't remember. Might try it again some day.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

------- Original Message -------

**Comment by mgmeyers** [comment]
This should now be fixed in the latest version of the plugin. Ignored suggestions will be remembered as long as the note remains open. They are only stored temporarily, however, and will be forgotten when a note is closed.
