### ISSUE TITLE
Better instructions for using LanguageTool Premium

### ISSUE THREAD

**Issue by danielnaber** [Clemens-E/obsidian-languagetool-plugin#49]
Hi @Clemens-E, I'm the founder of LanguageTool. I couldn't find your email address, so I'm opening this issue: We're getting quite a few requests from Premium users asking us to enable API access for them, so they can use LT Premium in Obsidian. I think we could streamline the documentation a bit, to make the process easier for users. Feel free to contact me about it at (firstname).(lastname)@languagetool.org.

**Comment by Clemens-E** [comment]
We have messaged previously, I will contact you again.

**Comment by rafo** [comment]
For me, as a premium user (thanks for the 20% offer) who has neither Word nor OpenOffice installed and does everything with Markdown: that would be the excellent news!

**Comment by Clemens-E** [comment]
We exchanged about making the process to get the required API Key easier and faster.
Premium Accounts already worked before.
You can read up on how to set up Premium in the Plugin here:
https://github.com/Clemens-E/obsidian-languagetool-plugin#premium-accounts
