### ISSUE TITLE
Popup gets cut off at editor edge

### ISSUE THREAD

**Issue by WakanaYuki** [Clemens-E/obsidian-languagetool-plugin#5]
Popups on the edge of the editor get cut off/you need to scroll to view the whole popup.
Maybe this is a way to fix this:
https://codemirror.net/demo/widget.html
https://codemirror.net/doc/manual.html#addLineWidget

**Comment by vulpes2** [comment]
I believe this is now fixed and can be closed.
![image](https://user-images.githubusercontent.com/83679347/121155241-a00ce480-c815-11eb-8eff-d10b98acb550.png)
