### ISSUE TITLE
more robust endpoint configuration

### ISSUE THREAD

**Issue by danielnaber** [Clemens-E/obsidian-languagetool-plugin#56]
We (LanguageTool) get feedback from users who get "request to LanguageTool failed" after having configured their premium API key. From the logs on our side, it looks as if these users might use the wrong endpoint. Could the endpoint configuration be made more robust, so that e.g. you cannot set `https://api.languagetoolplus.com` if it needs to be `https://api.languagetoolplus.com/v2/check` (or vice versa - I'm not sure what's the right setting).

**Comment by Clemens-E** [comment]
I can see how this is confusing, currently implementing a dropdown to make the URL selection more robust.

![Obsidian_CrSDs4EWAG](https://user-images.githubusercontent.com/43886026/157948192-bf4bb42c-4cb9-4f8f-97b3-bc384def1dc2.gif)

**Comment by felixmeyjr** [comment]
I'm still getting the issue, as described above from Mr. Naber. 

The HTTP Endpoint is copied from the Developer API from my LT Premium account:
Custom URL with `https://api.languagetoolplus.com/v2`. 

Api key and user-email is obviously set.

**Comment by LeehamElectronics** [comment]
I'm self hosting Languagetools in a Docker container and I am getting the following error:
```Failed to load resource: the server responded with a status of 400 (Bad Request)```

Any ideas? 
Thanks

**Comment by LeehamElectronics** [comment]
Solved, I just had to disable all these settings and enable auto detect in the plugin settings under Language Varieties. 
![image](https://user-images.githubusercontent.com/51737378/201501249-65df0eaf-9b83-4331-967d-bbadf8dfcbea.png)

**Comment by smonsec** [comment]
> Solved, I just had to disable all these settings and enable auto detect in the plugin settings under Language Varieties. ![image](https://user-images.githubusercontent.com/51737378/201501249-65df0eaf-9b83-4331-967d-bbadf8dfcbea.png)

Thanks a lot, I was banging my head with a wall, soon after installing I changed some of these settings, which ended up giving an error "request to LanguageTool failed". Going back to defaults solved it.
