### ISSUE TITLE
API key now in settings

### ISSUE THREAD

**Issue by fabiobruna** [Clemens-E/obsidian-languagetool-plugin#57]
FYI, you can now access your API key in your setting: https://languagetool.org/editor/settings/api No need to email them. Maybe change this in the readme.

Regards,
Fabio
​

**Comment by Clemens-E** [comment]
Hi, I was told by Daniel Naber to add that section, unless I get told otherwise I will leave it as is

fyi @danielnaber

**Comment by danielnaber** [comment]
The API key is only available at https://languagetool.org/editor/settings/api when our support has manually activated it, so you still need to email us.
