### ISSUE TITLE
I hope the syntax can be highlighted.

### ISSUE THREAD

**Issue by zxyyysabd123** [Clemens-E/obsidian-languagetool-plugin#58]
It's better if the syntax like \begin{equation}\end{equation} can be highlighted.

**Comment by Clemens-E** [comment]
I have no idea what you are talking about, could you elaborate?

**Comment by zxyyysabd123** [comment]
I hope the syntax can be highlighted. For example, 
''we have an equation as follows
\begin{eqaution}a+b=c\end{equation}''
,I hope syntax ''\begin{equation}... \end{equation}'' are colored blue while the text  "we have an equation as follows" is no colored specially.

**Comment by mgmeyers** [comment]
@zxyyysabd123 It doesn't seem like your issue is related to language tool. That being said, you have to wrap latex in `$` like `$\begin{equation}a+b=c\end{equation}$` to get syntax highlighting.
