### ISSUE TITLE
Add support for mother tongue option

### ISSUE THREAD

**Issue by Ellpeck** [Clemens-E/obsidian-languagetool-plugin#61]
Hi! I love this plugin and the features it provides, but I was wondering if you'd consider implementing an additional feature: Support for the LanguageTool API's `motherTongue` option, which causes the API to run additional checks related to the selected language in comparison to the mother tongue, for things like false friend terms.

According to the [HTTP API docs](https://languagetool.org/http-api/), it's just an additional option called `motherTongue`, and it's described as `A language code of the user's native language, enabling false friends checks for some language pairs.`

Thanks!

**Comment by Clemens-E** [comment]
I added it like described in the docs:
![grafik](https://github.com/Clemens-E/obsidian-languagetool-plugin/assets/43886026/27d4d7fb-c6e8-4977-b952-5db007534b8b)
I tried a few "false friends" between German and English but got no results.
But it's added 🤷‍♂️
