### ISSUE TITLE
Failed to install update 

### ISSUE THREAD

**Issue by gabrielcarus** [Clemens-E/obsidian-languagetool-plugin#62]
Tried to update the LanguageTool Plugin, and it didn't work. 
(The plugin itself is in perfect functioning, just this minor detail is bugged)

![image](https://user-images.githubusercontent.com/105552060/179744383-2a3fc486-cd7f-4c6e-a455-f23249820f77.png)

**Comment by pulsovi** [comment]
I have the same

**Comment by Clemens-E** [comment]
Should be fixed, forgot that Obsidian looks into the repo to check the latest version instead of checking the releases, for whatever reason.

**Comment by gabrielcarus** [comment]
Thank you for the fast response @Clemens-E, have a nice day ahead 🫂
