### ISSUE TITLE
How to change de spellcheck to another language?

### ISSUE THREAD

**Issue by EhuddR** [Clemens-E/obsidian-languagetool-plugin#7]
Hi! 

First of all this is a great tool. I'm wondering how do we can change the spellcheck language to Spanish for example? I'm not a programmer so I'm stuck whit the use of this plugin. 

I hope you can help me solve this issue. Thanks in advance.

Best Regards.

**Comment by Clemens-E** [comment]
Hi, the plugin tells LanguageTool to auto-detect the language, does this not work for you?
I found it quite reliable but I only write German and English, so I don't know for other languages.
I can add an overwrite if the auto-detection doesn't work for you.
I wrote the same in discord if you prefer to resolve the issue there

**Comment by EhuddR** [comment]
Hello, it seems that the plugin does not detect the Spanish language because at the time of making a revision in a note all the words are marked as error.The plugin tries to correct the words to English. I appreciate your help with this issue . 
Sorry, I didn't saw your response earlier.

**Comment by Clemens-E** [comment]
This would be a Problem with languagetool itself so I can't really fix this. I can only add a overwrite to notes so you can specify a language (but I'm unsure on whats the cleanest way for this).

Can you give me some text so I can reproduce this issue and maybe even report it to languagetool themselves?

**Comment by EhuddR** [comment]
The word "Accion" should be corrected to "Acción" however it is only corrected to English. 
![image](https://user-images.githubusercontent.com/78237982/113460575-df1a5600-93de-11eb-90a5-9a55bb1da2ba.png)

**Comment by EhuddR** [comment]
Hi! I do'nt know what exactly happened but the plugin is working now.

**Comment by leocb** [comment]
Had the same problem, I fixed it by adding the 2 languages I use on the _Obsidian_ options (not the extension)

Go to the options (The cog) -> Editor (second option from the top) scroll a bit down, and you should find Spellcheck languages, add the languages you need there.
