### ISSUE TITLE
URL to fetch API Key

### ISSUE THREAD

**Issue by jamieadamsuk** [Clemens-E/obsidian-languagetool-plugin#70]
I emailed LanguageTool to request an API key, and they helpfully directed me to this URL:

https://languagetool.org/editor/settings/api

Would be useful to add this to the docs.

**Comment by Clemens-E** [comment]
Would be useful if you read the previous tickets for this topic
#57 #67

**Comment by jamieadamsuk** [comment]
Ah. Apologies. The language confused me.
