### ISSUE TITLE
Using https://api.languagetoolplus.com/v2/ as the url throws error.

### ISSUE THREAD

**Issue by bruisedsamurai** [Clemens-E/obsidian-languagetool-plugin#72]

**Comment by bruisedsamurai** [comment]
I manually added the suffix. Yeah wasn't aware that `/v2/` is added automatically.

**Comment by Clemens-E** [comment]
Why enter the manual url at all?
You can just select the "Premium" URL preset

**Comment by bruisedsamurai** [comment]
I thought v2 would offer better capabilities.
