### ISSUE TITLE
First request succeeded but the second request failed on the self-hosted LanguageTool server

### ISSUE THREAD

**Issue by skywind3000** [Clemens-E/obsidian-languagetool-plugin#75]
Brief :

- I have hosted LanguageTool server myself at port 1081, the API is tested with curl.
- Click "Check current document" in the plugin popup menu, the errors can be detected as expected.
- Click "Check current document" again, the request seems hanging there and the progress icon in the status line continues rotating and never get stopped until I reset this plugin (disable and enable).

Environment:

- System: Windows 10
- Obsidian version: 1.0.3
- LanguageTool plugin version: 0.3.1
- LanguageTool version: 5.9

Steps to reproduce:

1\) Download the latest LanguageTool binary from:

- https://languagetool.org/download/LanguageTool-5.9.zip

2\) Extract the `.zip` file to somewhere and start the server in HTTP mode:

```bash
java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 1081 --allow-origin
```

Assuming you have Java Runtime installed and you may see to server log like:

```
2022-11-04 16:46:39 +0000 Starting LanguageTool 5.9 (build date: 2022-09-28 14:38:38 +0000, f8931be) server on http://localhost:1081...
2022-11-04 16:46:39 +0000 Server started
```

3\) Test it with curl:

```bash
curl -d "language=en-US" -d "text=a simple test" http://127.0.0.1:1081/v2/check
```

Make sure the API works. 

4\) Configure plugin: change `Endpoint` to `Custom URL` and set the URL to `http://127.0.0.1:1081'

![image](https://user-images.githubusercontent.com/3035071/200031300-2a3cf607-352a-4ea0-a303-6dff60e4ebaf.png)

5\) Start detection: click the status line button and select "Check current document"

![image](https://user-images.githubusercontent.com/3035071/200033403-3db13cee-2ac1-4982-a72e-0a8754268cb8.png)

Everything is OK until now, the request succeeded, errors are marked and I can click the errors to see the details.

5\) But when I click "Check current document" again, I got no response for a long time

![image](https://user-images.githubusercontent.com/3035071/200034345-8e0cb336-29d2-4728-961d-25e93506464b.png)

The progress icon keeps rotating in the status line, but never get a result until you reset this plugin.

6\) Every time I perform a grammar check I have to reset this plugin otherwise I can't use it any more.

7\) The LanguageTool server works fine any time I test it with curl.

Really love this plugin and hope the problem can be addressed.

**Comment by skywind3000** [comment]
more information:

- the second request seems not be received by the server: I can't see any new server log like the first request.

**Comment by Clemens-E** [comment]
Hi, did you change the notes content before  running the second check? Try just adding a character or similar.

The plugin caches requests, meaning if nothing changed, it will use the previous api result. Maybe that logic runs and causes the weird behaviour.

**Comment by skywind3000** [comment]
You are right. I didn't change the text before the second check.

The second request succeeded like the first one after adding a "hello, world" to the document.

**Comment by Clemens-E** [comment]
That's good right?
I will check why it won't stop loading properly

**Comment by skywind3000** [comment]
OK, this is a workaround that can be used temporarily.

Expecting your fix.

**Comment by burtbadbackarack** [comment]
Im new to a lot of this. 

With step 2, I have extracted the folder. But what does it mean to run in HTTP? 
Ive had a quick google, but its all too far a field for me.

**Comment by Clemens-E** [comment]
I fixed the caching, can you confirm @skywind3000 
You can test this by 
1. Press Check Text
2. Switch to different Note
3. Check Text again without making changes
4. corrections should appear immediately

**Comment by skywind3000** [comment]
thanks, it works like a charm now.
