### ISSUE TITLE
document new way to get a LanguageTool API key

### ISSUE THREAD

**Issue by danielnaber** [Clemens-E/obsidian-languagetool-plugin#76]
We have simplified the way users can get an API key for their LanguageTool premium account. The `README.md` could be adapted like this:

Old: 

> For you to receive an API Key, send a short notice to the LanguageTool support at [support@languagetoolplus.com](mailto:support@languagetoolplus.com), asking for it like "Please set an API key for my account, so I can use LanguageTool Premium with Obsidian."

Suggestion for new wording:

> You can generate your API key at https://languagetool.org/editor/settings/access-tokens

In other words, getting an API key is self-service now and there's no need anymore to contact our support team.

**Comment by tophee** [comment]
So, this means that it is no longer possible to access the API with a free account?

**Comment by danielnaber** [comment]
Nothing changes for the free API (https://dev.languagetool.org/public-http-api), this is just about how to get a Premium API key.
