### ISSUE TITLE
[UX]Interaction with plugin suggestion is not quick.

### ISSUE THREAD

**Issue by bruisedsamurai** [Clemens-E/obsidian-languagetool-plugin#77]
When there are suggestions from the plugin. Often it takes some time for the plugin to show the suggestion box. It would be better if it opens as fast as I click on it.

I understand the 1 query per 3 seconds, but other things can be optimized.

Moreover, would it be possible if the colouring is real time too? Currently, If I add some words in between, the highlighting remains there for sometime before moving it back to the correct position.

**Comment by Clemens-E** [comment]
No clue what you are referring to, when I click on a suggestion it pops up immediately and colouring disappears fast too.
Maybe record a video and provide explicit steps how to reproduce the issue.

**Comment by bruisedsamurai** [comment]
Will do

**Comment by dannymate** [comment]
Here is an example of how long language tool takes to respond to a spelling misake.

[Screencast from 2023-01-20 20-17-40.webm](https://user-images.githubusercontent.com/26135914/213800543-459bc865-8f09-46d2-80cb-a99f48570bb7.webm)

**Comment by Clemens-E** [comment]
Uhm, yeah, are you referring to the time it takes to highlight the text after you stopped typing?
That's called a debounce to prevent flooding the API with requests when you only stop typing for a second

**Comment by Clemens-E** [comment]
Closing this as after no further clarification from the author.
