### ISSUE TITLE
request to LanguageTool failed on android app

### ISSUE THREAD

**Issue by yiwkd2** [Clemens-E/obsidian-languagetool-plugin#78]
In android app, requests to LT are failed.
Is this a bug that can be fixed easily?

**Comment by Clemens-E** [comment]
The plugin works on Android, so it's probably something with your note or, more likely your configuration

**Comment by yiwkd2** [comment]
I figured when it happens.
If I set Language varieties (English - English (US)) in android, requests start failing.
When I leave it ---, it works fine as you said.
There is no issue in the windows app with the same vault and configuration.

**Comment by Clemens-E** [comment]
I can't replicate this, is your "static language" on auto detect?

**Comment by yiwkd2** [comment]
Oh, you're right. Thank you.
