### ISSUE TITLE
feature request: Add login for languagetool pro.

### ISSUE THREAD

**Issue by cocoonkid** [Clemens-E/obsidian-languagetool-plugin#8]
feature request: Add login for languagetool pro.

thank you so much

**Comment by Clemens-E** [comment]
looked into this and as it seems it's just a few headers.
I have finals coming up, so I don't want to promise anything. I will do it no later than in 3 weeks, but hopefully sooner

**Comment by cocoonkid** [comment]
Take all the time you need!

**Comment by Clemens-E** [comment]
I implemented this like its described in the [swagger](https://languagetoolplus.com/http-api/#!/default/post_check) and got someone from the obsidian community to test it (because I don't have LanguageTool Premium). But as it turns out, Premium Users do not get access to the premium API like I assumed (see [api section](https://languagetool.org/editor/settings/api))

I assume the extension manages this over the user session, I *think* to make it work I would need to reverse engineer that and store the session information. I really don't want to do that because its too much effort and violates TOS

**Comment by Mara-Li** [comment]
Hello ! I can test the premium :) 
The problem ? I can't install it from the plugin community in the app.

**Comment by cocoonkid** [comment]
I'm really sorry and please accept my apology for having wasted your time with this request.

I coulnd't believe and  verified myself. It is true and a true waste of their business...I just canceled my subscription with them.

They didn't even bother to add add a fix all errors button in 2 years..You have to click as many times as there are suggestions.

Again sorry and thanks for your time and patience anyways.

**Comment by Clemens-E** [comment]
The only way to access it, is paying 39€ per month for 250 API calls per day. Why even have the premium tier for normal users in the first place.
Anyway, no hard feelings, I luckily didn't waste *that* much time on this

**Comment by cocoonkid** [comment]
Absolutely agreed.

**Comment by kruemel746** [comment]
I kindly asked for an API key for the specific purpose with a premium access. They were very friendly and provided it to me at no extra cost. I don't think they primarily considered this intended use.
Your premium integration works great!

**Comment by Biszkoptu** [comment]
Hey @kruemel746!
I just asked for the API key and received it as well. Unfortunately, it seems that it is not working for me. I don't know whether I should wait (I received it a couple of minutes ago). Maybe I did something wrong in settings, but I think I tried every reasonable combination. Let me know how were you able to use the premium API :)

**Comment by Biszkoptu** [comment]
I was able to find the source of the problem.
I should have used the `https://api.languagetoolplus.com` instead of `https://api.languagetoolplus.com/v2/` link as an endpoint.

**Comment by Jetlagger** [comment]
Hey, just want to confirm that I as well asked about Premium access on the API and was promptly provided with a key :)
And indeed, you have to use `https://api.languagetoolplus.com`

**Comment by Clemens-E** [comment]
Premium is now officially supported, see the README.
