### ISSUE TITLE
Supporting API v2

### ISSUE THREAD

**Issue by xplosionmind** [Clemens-E/obsidian-languagetool-plugin#84]
As of right now, to make any official LanguageTool client/extension work with one’s own self-hosted LT server, it is necessary to append `/v2` to the server address.

With this plugin, appending `/v2` makes the spell-checking to stop working. This means that this plugin is still using API v1. It would be super useful to implement it with v2, in order to enable more features such as #59, #71, and #73.

Thanks a lot for developing and maintaining this plugin, it is extremely useful!

Best,
T

**Comment by Clemens-E** [comment]
> With this plugin, appending /v2 makes the spell-checking to stop working

Because it already appends /v2 to any URL you feed it, it's always using the /v2 API.
When you add /v2 yourself, it uses `yourdomain.com/v2/v2/check` leading to your error.
You can use the new "Copy failed Request Logs" Button in the Settings to spot things like this in the feature.

**Comment by xplosionmind** [comment]
Thanks a lot for clarifying!
