### ISSUE TITLE
License

### ISSUE THREAD

**Issue by michenriksen** [Clemens-E/obsidian-languagetool-plugin#85]
Hi there! I'm wondering what the license is for this project?

Thanks!

**Comment by stdedos** [comment]
https://github.com/Clemens-E/obsidian-languagetool-plugin/blob/b70c136ec22ba423ea223e165e54509231a0c3e0/package.json#L30

https://choosealicense.com/licenses/unlicense/:

> <h1 style="font-size: 2.1875rem; margin: 0.67em 0px 25px; color: rgb(68, 68, 68); font-family: Chivo, &quot;Helvetica Neue&quot;, Helvetica, Arial, serif; font-weight: 900; line-height: 1.1; max-width: 700px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The Unlicense</h1><div class="clearfix" style="color: rgb(92, 88, 85); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="license-body" style="font-size: 0.9375rem; float: left; width: 700px;"><p style="margin-bottom: 1em;">A license with no conditions whatsoever which dedicates works to the public domain. Unlicensed works, modifications, and larger works may be distributed under different terms and without source code.</p><div class="license-page-details" style="box-sizing: border-box;">
> 
> Permissions | Conditions | Limitations
> -- | -- | --
> Commercial use |   | Liability
> Distribution |   | Warranty
> Modification |  |
> Private use | | 
> 
> </div></div></div>

**Comment by Clemens-E** [comment]
@stdedos 
That's entirely wrong.
`UNLICENSED` does not mean `The Unlicense` (notice the missing d), it's meant as the literal definition of the verb "unlicensed", meaning there is no License set and I retain the full copyright of the software.
You can read this up on Wikipedia:
> Contrary to popular belief, distributed unlicensed software (not in the public domain) is fully copyright protected, and therefore legally unusable (as no usage rights at all are granted by a license)

Also, a single note in package.json is not enough for anything, so michenriksen is correct to ask for a clarification.
This is not really something I did purposely because I hate sharing code, it's just something I do when I haven't decided on a license yet.

**Comment by michenriksen** [comment]
@Clemens-E thanks for your answer! Do you plan to decide on a license any time soon? I have been working on a plugin using yours as a base as I couldn't get my own highlighting implementation to work for some reason 😕 but I unfortunately didn't pay attention to the licensing and now i'm blocked on the release. If you decide on a permissive license, I will of course give you credit for doing all the hard work! 🙇 

Anyway, I respect whatever decision you make; thanks for developing this awesome plugin!

**Comment by Clemens-E** [comment]
I'm thinking of using https://polyformproject.org/licenses/noncommercial/1.0.0/ or https://polyformproject.org/licenses/strict/1.0.0/ as licence, basically meaning any non-commercial purpose is a permitted purpose.

Of course, I can only do this for my code parts, @mgmeyers who wrote a substantial amount of the code has to decide for their parts, and other people who have contributed code (e.g. @PatrickRoethlisberger)

Generally, I don't think anyone minds if you took a peek at how this plugin handles highlighting 😄

**Comment by mgmeyers** [comment]
I here by give away all rights to any code I wrote for this plugin to @Clemens-E 👨‍⚖️

**Comment by michenriksen** [comment]
@Clemens-E Nice! Those are some interesting options. I'm personally totally fine with the non-commercial one, but as far as I understand, the strict version does not allow forks/modifications to the original source? That would be sad, IMO.

If you decide on a non-commercial license, remember to update the description in the Obsidian plugin directory to make that clear, as I think many people could be using your plugin for work related tasks.

Cheers!

**Comment by PatrickRoethlisberger** [comment]
I, personally, would prefer a more open License like MIT, but understand why choosing a more restrecive one makes sense.
Anyhow you decide, I hereby give away all rights to any code I wrote for this plugin to @Clemens-E .

**Comment by michenriksen** [comment]
> I, personally, would prefer a more open License like MIT

I agree, MIT or similar well-known, permissive license would be ideal in this case. Publishing an already established plugin under a noncommercial license could be very tricky, as I imagine many people already use it for work related tasks, especially if they are paying for Obsidian Commercial and LanguageTool Premium/Business.

Anyway, just my thoughts. 🙂

**Comment by PatrickRoethlisberger** [comment]
I, for example, use the extension for work related tasks and hope to still be able using it for those (which I'm not entirely sure whether I'd be able with the mentioned licenses).

**Comment by stdedos** [comment]
Just go bonkers with [GNU AGPLv3](https://choosealicense.com/licenses/agpl-3.0/).

I mean, "sure", they are able to do _whatever you said_, and they **must** disclose source, and give you full credit.
I guess that's the "best deal" you can give them. Also, a lot of companies are "scared" to take in AGPL, so, that could be a deterrent here & now.

**Comment by Clemens-E** [comment]
I'm not trying to be snarky, but being mentioned in the bottom of some readme means nothing to me while a company makes an unknown amount of revenue with a user base that wouldn't even know their service without a community made plugin, where they also had no work to invest in.

Not sure, isn't Attribution-NonCommercial-NoDerivatives 4.0 International similar to the non-commercial clause of the PolyForm Noncommercial License when it comes to commercial use? 

I'm thinking I will use the PolyForm Licence and make small adjustments to it that allows everyone to use the Plugin, but not to make changes/redistribute it for commercial purposes.

**Comment by stdedos** [comment]
_Well, maybe I should've started with an IANAL preface_ 😅 

> I'm not trying to be snarky, but being mentioned in the bottom of some readme means nothing to me while a company makes an unknown amount of revenue with a user base that wouldn't even know their service without a community made plugin, where they also had no work to invest in.

Oh no! I didn't mean "you should settle for that" 😅 

I was attacking the other part of AGPL (they **must** disclose source). Which means, you can leverage their work on your free product. "You will still loose a couple of people" who "just want to pay", but idk why would anyone compare to equivalent plugins and choose to go for 8€/mo one or something ...

> they could launch the Official Plugin™️ relatively quickly regardless.

Yeah 😕 and definitely it's expensive to attack someone who "functionally" does the same things as you. "Maybe" having an FSF/OSI license makes it easier to attack them? idk 🤷 

_I'm in this journey to learn by interaction, pardon my ignorance. Also IANAL._

**Comment by michenriksen** [comment]
It looks like license was changed to [MIT on March 20, 2021](https://github.com/Clemens-E/obsidian-languagetool-plugin/commit/2007168e6392abc97c6c870761b30358e3ade0d8#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) and then back to [UNLICENSED on October 24, 2022](https://github.com/Clemens-E/obsidian-languagetool-plugin/commit/49510c25e081ea6ae347994c6d283728692fc586)?

**Comment by Clemens-E** [comment]
As already said, a three-letter word does not replace a full license text, a mere mention of MIT does not specify the license for the source code.

I added GNU AGPLv3, see [LICENSE.md
](https://github.com/Clemens-E/obsidian-languagetool-plugin/blob/master/LICENSE.md)

**Comment by stdedos** [comment]
I'd still do a favor on the parsing tools and add the related `license:` key on the `package.json`

Up to you of course
