### ISSUE TITLE
Customizable Debounce

### ISSUE THREAD

**Issue by dannymate** [Clemens-E/obsidian-languagetool-plugin#89]
[Screencast from 2023-01-20 20-17-40.webm](https://user-images.githubusercontent.com/26135914/213810212-57eb0678-ea22-4969-96dd-5386adfd2549.webm)

Follwing up from https://github.com/Clemens-E/obsidian-languagetool-plugin/issues/77.

Would it be possible to customise the length of the debounce?
If not for central instances then at least when running your own instance of LanguageTool? 
Maybe having a set range of times to pick from. 

I don't mind adding this feature myself and creating a pull request (trying anyway). Just want your opinion first. Thanks.

**Comment by Clemens-E** [comment]
Sure, just adjust [the debounce timeout](https://github.com/Clemens-E/obsidian-languagetool-plugin/blob/master/src/cm6/buildAutoCheckHandler.ts#L31)
with a configurable setting in [the settings tab](https://github.com/Clemens-E/obsidian-languagetool-plugin/blob/master/src/SettingsTab.ts)

should probably add some kind of disclaimer on [the rate limits for official apis](https://languagetool.org/http-api/)
If it works for you, I can commit that disclaimer into your pr branch after you created it

**Comment by dannymate** [comment]
That's great thanks! I'll give it a go and let you know.

In regards to the disclaimer, that's fine with me.
