### ISSUE TITLE
spell check is not set to English, how can I set it to English?

### ISSUE THREAD

**Issue by santiyounger** [Clemens-E/obsidian-languagetool-plugin#9]
Thanks for making this plugin.

I'm not sure what's going on with my set up 
I just installed it, however the spellcheck is not in English
![image](https://user-images.githubusercontent.com/51902730/118196152-1fbfb300-b412-11eb-9124-6b7c038d91ae.png)

This is what I have by default in the plugin settings
`https://api.languagetool.org/v2/check`

Any idea on how to change it to English thank you!

**Comment by Clemens-E** [comment]
The plugin relies on the language tool API to detect the language. Just try writing a full sentence (or multiple words of the language) and it should detect it.

**Comment by santiyounger** [comment]
Got you it worked now that I added more words. Would it be possible to choose English as a default? Or perhaps select 2 or 3 languages and only have the plugin correct in those languages?

That'd be amazing, since I only ever write in English and Spanish. Having the other languages can definitely be intrusive at times.

Would love to hear your thoughts on this, since I might be wrong and it might not be an essential thing to have in the plugin in settings
thanks!

**Comment by Clemens-E** [comment]
I never had a problem with LanguageTool detecting the wrong language, so I didn't add this, but since this is the secondish time someone asks for it, I guess I will add a default language option.

About the multiple languages, I don't think this is something I can really implement because I rely on https://languagetoolplus.com/http-api/#!/default/post_check which only allows auto-detecting languages, or using a specified one.

**Comment by santiyounger** [comment]
thanks a lot for considering it. A default language sounds good. If it's easy to change language in the plugin settings, perhaps a multi-language setup isn't necessary. Sounds like a great plan Thanks

**Comment by santiyounger** [comment]
thanks a lot for considering it. A default language sounds good. If it's easy to change language in the plugin settings, perhaps a multi-language setup isn't necessary. Sounds like a great plan Thanks
