### ISSUE TITLE
AI | Full sentence rewrite functionality?

### ISSUE THREAD

**Issue by bdemirjian** [Clemens-E/obsidian-languagetool-plugin#91]
The new feature MAJOR added that allows for full sentence rewrite...

Any chance of adding it?

**Comment by Bearsaerker** [comment]
I'd love to see that as well!

**Comment by Clemens-E** [comment]
I don't think the rewrite feature is a public API, at least I can't find it in LanguageTool's Swagger Documentation.
Also, the endpoint doesn't accept the API tokens that the plugin normally uses.
