### ISSUE TITLE
Hitting a character limit despite less than 150,000 characters 

### ISSUE THREAD

**Issue by Chrismarsh** [Clemens-E/obsidian-languagetool-plugin#99]
I have a text that is 75635 characters (as per Obsidian footer) which should be well under the 150,000 character limit.  However, the logs shows
```
url used for request: https://api.languagetoolplus.com/v2/check
Status: 413
Body: Error: Your text exceeds the limit of 60000 characters (it's 68898 characters). Please submit a shorter text.
Settings: {"serverUrl":"[https://api.languagetoolplus.com","urlMode":"premium","glassBg":true,"shouldAutoCheck":false,"pickyMode":true,"username":"REDACTED","apikey":"REDACTED","staticLanguage":"en-CA"](https://api.languagetoolplus.com%22,%22urlMode%22:%22premium%22,%22glassBg%22:true,%22shouldAutoCheck%22:false,%22pickyMode%22:true,%22username%22:%22REDACTED%22,%22apikey%22:%22REDACTED%22,%22staticLanguage%22:%22en-CA%22)}
```

I've confirmed with LT support that this should be fine on their end. It's unclear to me why the logs are showing that 60k characters is the limit as that's not correct.

**Comment by Clemens-E** [comment]
The message "Your text exceeds the limit of 60000 characters [...]" comes from the LanguageTool API.
My only guess would be that they have the 150k limit for raw text, but we send a JSON to exclude markup from the check.
Sorry, but I can't help you, your only option is selecting a section of the text and running the check (that only checks that selection)
